[features]
seeds = false
[programs.devnet]
contract = "4wVU7fKYq1Yw5pRvEfVqF3cxJFycdg7SJCF9BpT3zGqm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/matvey/.config/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"